from __future__ import annotations

from dataclasses import dataclass
from math import ceil

from ..constants import (
    BASE_PRICES,
    CONSUMER_FOOD_BASE_UNITS_PER_100_POP,
    CONSUMER_GOODS_BASE_UNITS_PER_100_POP,
    CONSUMER_GOODS_WEALTH_STEP_DOLLOPS,
    CONSUMER_GOODS_WEALTH_STEP_UNITS,
    CONSUMER_EDUCATION_SEASONAL_UNITS,
    CONSUMER_HEALTH_BASE_SEASONAL_UNITS,
    CONSUMER_HEALTH_CASUALTY_UNITS,
    CONSUMER_VACCINE_SEASONAL_UNITS,
)
from ..models.market import Market, MarketOffer
from ..models.player import Player
from ..models.resource import ResourceType


@dataclass(frozen=True)
class ConsumerDemandPlan:
    units: dict[ResourceType, int]


@dataclass(frozen=True)
class ConsumerPurchaseResult:
    player_id: int
    player_name: str
    bought: dict[ResourceType, int]
    spent: float
    unmet: dict[ResourceType, int]


def consumer_demand_plan(
    player: Player,
    season_name: str,
    casualties: int = 0,
) -> ConsumerDemandPlan:
    """End-product demand generated by resident households for one season."""
    population_units = max(0, ceil(player.population / 100))
    units: dict[ResourceType, int] = {}
    if population_units > 0:
        food_units = population_units * CONSUMER_FOOD_BASE_UNITS_PER_100_POP
        if food_units > 0:
            units[ResourceType.FOOD] = food_units

        wealth_steps = int(max(0.0, player.dollops) // CONSUMER_GOODS_WEALTH_STEP_DOLLOPS)
        goods_units = (
            population_units * CONSUMER_GOODS_BASE_UNITS_PER_100_POP
            + wealth_steps * CONSUMER_GOODS_WEALTH_STEP_UNITS
        )
        if goods_units > 0:
            units[ResourceType.GOODS] = goods_units

        health_units = CONSUMER_HEALTH_BASE_SEASONAL_UNITS.get(season_name, 0)
        health_units *= population_units
        health_units += casualties * CONSUMER_HEALTH_CASUALTY_UNITS
        if health_units > 0:
            units[ResourceType.HEALTH_SERVICES] = health_units

        vaccine_units = CONSUMER_VACCINE_SEASONAL_UNITS.get(season_name, 0)
        vaccine_units *= population_units
        if vaccine_units > 0:
            units[ResourceType.VACCINE] = vaccine_units

        education_units = CONSUMER_EDUCATION_SEASONAL_UNITS.get(season_name, 0)
        education_units *= population_units
        if education_units > 0:
            units[ResourceType.COURSES] = education_units
    return ConsumerDemandPlan(units=units)


def structural_consumer_demand_units(
    output: ResourceType,
    all_players: list[Player],
    season_name: str,
) -> float:
    return float(
        sum(
            consumer_demand_plan(player, season_name).units.get(output, 0)
            for player in all_players
        )
    )


def buy_household_goods_from_offers(
    player: Player,
    market: Market,
    desired: dict[ResourceType, int],
    post_unmet: bool = True,
) -> ConsumerPurchaseResult:
    bought: dict[ResourceType, int] = {}
    unmet: dict[ResourceType, int] = {}
    total_spent = 0.0

    for rtype, qty in desired.items():
        remaining = max(0, int(qty))
        if remaining <= 0:
            continue
        spent_on_resource = 0.0
        for offer in market.available_offers(rtype):
            if remaining <= 0 or player.household_cash <= 0:
                break
            take, cost = _affordable_fill(player.household_cash, offer, remaining)
            if take <= 0:
                break
            offer.remaining -= take
            player.household_cash = round(player.household_cash - cost, 2)
            total_spent = round(total_spent + cost, 2)
            spent_on_resource = round(spent_on_resource + cost, 2)
            remaining -= take
            bought[rtype] = bought.get(rtype, 0) + take
            if offer._seller is not None:
                offer._seller.receive_dollops(cost)
            if market.telemetry is not None:
                market.telemetry.record_traded(rtype, take)
                market.telemetry.record_consumed(rtype, take)
        if remaining > 0:
            unmet[rtype] = remaining
            if post_unmet:
                market.post_demand(rtype, remaining)
        filled = bought.get(rtype, 0)
        if filled > 0:
            avg = spent_on_resource / filled if spent_on_resource else BASE_PRICES[rtype.value]
            market._emit_market_event(rtype, "ask", "filled", avg, filled, "Households")

    return ConsumerPurchaseResult(
        player_id=player.player_id,
        player_name=player.name,
        bought=bought,
        spent=round(total_spent, 2),
        unmet=unmet,
    )


def _affordable_fill(
    household_cash: float,
    offer: MarketOffer,
    remaining: int,
) -> tuple[int, float]:
    max_by_qty = min(remaining, offer.remaining)
    max_by_cash = int(household_cash // offer.price_per_unit)
    take = min(max_by_qty, max_by_cash)
    return take, round(take * offer.price_per_unit, 2)
